version: '3.8'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT:-8000}

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  pgdata:
