name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ragdb
          POSTGRES_USER: rag
          POSTGRES_PASSWORD: ragpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U rag -d ragdb" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: postgresql://rag:ragpass@localhost:5432/ragdb
      VECTOR_PROVIDER: CHROMA
      OPENAI_API_KEY: test_key_for_ci
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do pg_isready -h localhost -p 5432 -U rag && break || sleep 1; done

      - name: Run tests
        run: |
          pytest -q
